spring:
  datasource:
    url: jdbc:mysql://183.99.247.17:12787/test_db
    username: root
    password: 1111
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #       show_sql: true
        format_sql: true
        default_batch_fetch_size: 100